FROM python:3.9.21-bookworm

COPY requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt

# TODO: Define code that runs the backend (currently its scripts expected to be run 1 after another manually)
CMD ["sleep", "infinity"]